#!/usr/bin/env bats

############################ DO NOT EDIT THIS FILE #####################################
# File: assignement_tests.sh
# 
# DO NOT EDIT THIS FILE
#
# Add/Edit Student tests in student_tests.sh
# 
# All tests in this file must pass - it is used as part of grading!
########################################################################################

@test "Pipes" {
    run "./dsh" <<EOF                
ls | grep dshlib.c
EOF

    # Strip all whitespace (spaces, tabs, newlines) from the output
    stripped_output=$(echo "$output" | tr -d '[:space:]')

    # Expected output with all whitespace removed for easier matching
    expected_output="dshlib.clocalmodedsh4>dsh4>cmdloopreturned0"

    # Debugging output
    echo "Captured stdout:" 
    echo "Output: $output"
    echo "Stripped Output: $stripped_output"
    echo "Expected Output: $expected_output"
    echo "Exit Status: $status"

    # Check exact match
    if [ "$stripped_output" != "$expected_output" ]; then
        echo "Test failed: Output does not match expected output."
        echo "Actual Output: $stripped_output"
        echo "Expected Output: $expected_output"
    fi

    # Assertions
    [ "$status" -eq 0 ]
}